/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f5',
        'surface-dim': '#dcdad6',
        'surface-bright': '#fcf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ef',
        'surface-container': '#f0ede9',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e5e2de',
        'on-surface': '#1c1c1a',
        'on-surface-variant': '#464554',
        'inverse-surface': '#31302e',
        'inverse-on-surface': '#f3f0ec',
        outline: '#767586',
        'outline-variant': '#c6c5d7',
        'surface-tint': '#484bd6',
        primary: '#2c2abc',
        'on-primary': '#ffffff',
        'primary-container': '#4648d4',
        'on-primary-container': '#d1d1ff',
        'inverse-primary': '#c0c1ff',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#0c714d',
        tertiary: '#8e0028',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#dc2c4f',
        'on-tertiary-container': '#ffc7ca',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#06006c',
        'on-primary-fixed-variant': '#2e2ebe',
        'secondary-fixed': '#9df4c8',
        'secondary-fixed-dim': '#81d8ad',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#920029',
        background: '#fcf9f5',
        'on-background': '#1c1c1a',
        'surface-variant': '#e5e2de',
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-lg-mobile': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'body-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Outfit', 'sans-serif'],
        'label-md': ['Outfit', 'sans-serif'],
        'label-sm': ['Outfit', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '20px',
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}